### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TheBaconSpace** [Rayzr522/SharpBot#1]
Would it be possible to have a Branch For using with bot with out having to use the selfbot

**Comment by Rayzr522** [comment]
That might be possible, but it would require rewriting some of the command handling. I'll certainly look into it. With a touch of magic, I might even be able to make a switch in the config file to toggle between selfbot/userbot mode.

**Comment by TheBaconSpace** [comment]
Hey Mind if i Suggest Using @BaconHawk FrameWork?

**Comment by Rayzr522** [comment]
Thanks, but my command system is quite nice :)

**Comment by TheBaconSpace** [comment]
@Rayzr522 Are You on Discord So We Can Chat? on there

**Comment by Rayzr522** [comment]
https://discord.io/rayzrdev-offical

**Comment by Rayzr522** [comment]
Sorry, the invite broke again. https://discord.gg/A6TRWVH
