### ISSUE TITLE
is not Starting

### ISSUE THREAD

**Issue by TheMaxFlame** [Rayzr522/SharpBot#18]
I have all the things set but it wont start is saying

![image](https://cloud.githubusercontent.com/assets/24374353/25045374/de75c7f8-2190-11e7-9a70-33245a2788e0.png)

**Comment by Rayzr522** [comment]
You have an invalid `config.json`. Please post the contents of your config [on hastebin](http://hastebin.com).

**Comment by abyssvi** [comment]
# Seriously though, censor your token. Preferably all of it.

Not doing so can let anyone that can read these posts (ie: everyone) log into your account.
