### ISSUE TITLE
How to use this with PM2?

### ISSUE THREAD

**Issue by Mason1128** [Rayzr522/SharpBot#37]
Title says it all.

**Comment by abyssvi** [comment]
We do not currently support pm2, so I can't give you a strong answer. If something as simple as pm2 start isn't working, you'll need to play around with it and get it to work yourself.

I'd strongly advise joining the discord server at https://discord.io/rayzrdevofficial - there's a few developers and some other people that may be willing to work with you on this.

**Comment by Rayzr522** [comment]
pm2 isn't officially supported, but it should be as simple as running `pm2 start src/bot.js` from inside the SharpBot folder.
