### ISSUE TITLE
//quote has Incorrect time

### ISSUE THREAD

**Issue by ipodtouch0218** [Rayzr522/SharpBot#39]
When using //quote to quote a message, the time that is put into the embed is the time //quote command was sent, instead of when the quoted message was sent.

[Example
](https://gyazo.com/984f0ba455bf3a07bc3671c3b48a459f)

**Comment by Rayzr522** [comment]
Did you edit the message right before quoting it? If you did, it uses the timestamp of the last edit.

**Comment by Rayzr522** [comment]
Fixed in the latest update. `git pull` to update.
