### ISSUE TITLE
setgame not working

### ISSUE THREAD

**Issue by lbdBG** [Rayzr522/SharpBot#7]
It just doesn't work. Does not give any output in the cosole but says: "Game changed ........"
Nothing else... **Absolutely nothing**

**Comment by Rayzr522** [comment]
Your game won't show for you, only for other people. This is a problem with Discord itself, not my bot. All selfbots have this problem. It's sending an embed when you do the command, right?

**Comment by lbdBG** [comment]
Yeah it is sending

**Comment by lbdBG** [comment]
Okay then, thanks :) 👍
