### ISSUE TITLE
Censor token?

### ISSUE THREAD

**Issue by xshotD** [Rayzr522/SharpBot#8]
I eval'd bot.token in my selfbot and it came out with the full token.

You may want to censor it for... you know safety/security

**Comment by Rayzr522** [comment]
Or just don't eval bot.token... I don't really want to filter the output of //eval

**Comment by xshotD** [comment]
Ah, okay.

**Comment by ChromaHosting** [comment]
noob

**Comment by xshotD** [comment]
It was in a private testing server.
